#!/bin/bash

DATA_DIR=${1:-./data}

docker run \
    --rm -it \
    --name devdisp \
    -v `realpath $DATA_DIR`:/root/data \
    -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 \
    -e DISPLAY=:0.0 \
    -e COLUMNS="`tput cols`" -e LINES="`tput lines`" \
    --net=host \
    fertilis/display:1.0 \
    devdispapp "${@:2}"
