#!/bin/bash

mkdir -p /tmp/display-shared/X11-unix
chmod -f 0777 /tmp/display-shared/X11-unix || true

docker run \
    --rm -it \
    -v /tmp/display-shared:/root/shared \
    -v /tmp/display-shared/X11-unix:/tmp/.X11-unix \
    -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 \
    -e COLUMNS="`tput cols`" -e LINES="`tput lines`" \
    -e DISPLAY=':0.0' \
    --ipc="host" \
    fertilis/display:1.0 \
    "${@:1}"
